image: Visual Studio 2019                           
                                                          
before_build:
  - nuget restore HW2_5_1/Solution/Solution.sln

build_script:
  - msbuild HW2_5_1/Solution/Solution.sln

test_script:
  - dotnet test HW2_5_1/Solution/Solution.sln