image: Visual Studio 2019                           

branches:
  except:
    - master

environment:
  matrix:
    - branch: (get-item env:APPVEYOR_REPO_BRANCH).Value

before_build:
  - nuget restore (%branch%/Solution/Solution.sln)

build_script:
  - msbuild %branch%/Solution/Solution.sln

test_script:
  - dotnet test %branch%/Solution/Solution.sln