image: Visual Studio 2019

install:
  - git clone https://github.com/F5DXWsqPme C:\projects\homework
  - git checkout (get-item env:APPVEYOR_REPO_BRANCH)

before_build:
  - nuget restore (get-item env:APPVEYOR_REPO_BRANCH).Value/Solution.sln

build:
  project: (get-item env:APPVEYOR_REPO_BRANCH).Value/Solution.sln

test_script:
  - dotnet test (get-item env:APPVEYOR_REPO_BRANCH).Value/Solution.sln