image: Visual Studio 2019                           
                
matrix:
  environment:
    - solution_name: HW2_6_1
                                          
before_build:
  - nuget restore %solution_name%/%solution_name%.sln

build_script:
  - msbuild %solution_name%/%solution_name%.sln

test_script:
  - dotnet test %solution_name%/%solution_name%.sln