image: Visual Studio 2019               
 
platform:
    - x86
    - x64

configuration:
    - Debug
    - Release

before_build:
  - cmd: before_build.bat

build_script:
  - cmd: build_script.bat

test_script:
  - cmd: test_script.bat