image: Visual Studio 2019

before_build:
  - nuget restore (get-item env:APPVEYOR_REPO_BRANCH).Value/Solution.sln

build:
  project: (get-item env:APPVEYOR_REPO_BRANCH).Value/Solution.sln

test_script:
  - dotnet test (get-item env:APPVEYOR_REPO_BRANCH).Value/Solution.sln